# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1b2690f9-4d1f-4d83-837b-a648f0f05131";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1d59e51c-1bbe-4a6e-af29-fa320b1dc556" = {
    device = "/dev/disk/by-uuid/1d59e51c-1bbe-4a6e-af29-fa320b1dc556";
    allowDiscards = true;
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DCBC-7A72";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/stuff" =
    { device = "/dev/disk/by-uuid/A6F49096F4906A77";
      fsType = "ntfs-3g";
      options = ["ro"];
    };

  fileSystems."/mnt/cwin" =
    { device = "/dev/disk/by-uuid/6404C1A304C17896";
      fsType = "ntfs-3g";
      options = ["ro"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/85c785f8-dc56-4ab2-9c6a-2ae0bb994322"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
